### ISSUE TITLE
[Feature request] Netscape format support

### ISSUE THREAD

**Issue by xhlove** [null93/milk-cookie-manager#11]
Some software use Netscape format cookies, just like aria2c, curl and etc.
It is possible to support ?

**Comment by null93** [comment]
Hello! Are you talking about being able to export cookies to [this](https://curl.haxx.se/docs/http-cookies.html) format? It is easily do-able, I just don't know how helpful it would be overall. It seems to me that it is an outdated format.

**Comment by xhlove** [comment]
I prefer to import this format cookies to chrome for use, because I can not find an extension which support this feature. And the other reason is that some old script/software still use this format cookies file. I know I can convert its format easily, but people are always lazy...
