### ISSUE TITLE
Feature Request: Allow cookies export into clipboard

### ISSUE THREAD

**Issue by NightMean** [null93/milk-cookie-manager#67]
As a long time user of EditThisCookie extension, I switched to Milk as I like it way more. 
What I'm currently missing is an option to copy all cookies into clipboard and pasting them into some field so they can be easily restored without saving the cookies into a file. 

I use this feature in EditThisCookie every time when I need to test something from one browser into another. 
It's much faster to do it like that instead of the actual file. 
Would it be possible to add it?

**Comment by null93** [comment]
Sorry for the VERY late reply. I've been really busy. I don't think I want something like that. I am really happy with importing and exporting files.

I get where you are coming from, but it would just be too much work. If you want to tackle it, I would consider merging in you PR :)

Best of luck! Closing for now, reopen if you see fit
