### ISSUE TITLE
Bug Invalid Cookie Store Id When Create a New Cookie

### ISSUE THREAD

**Issue by teguh02** [null93/milk-cookie-manager#72]
Hi, i'm new user from this extension, i'm was trying to create a new cookie using my firefox browser, but when i click a create cookie button. I still facing "Error: Invalid Cookie Store Id 0" below

Before Click The Create Cookie Button
![image](https://github.com/null93/milk-cookie-manager/assets/43981051/1de0d3e9-6f8d-40ed-8d95-8bab9a5c3bcf)

After Click The Create Cookie Button
![image](https://github.com/null93/milk-cookie-manager/assets/43981051/63d0482d-86a7-416b-a866-7a9e1c1c3bb6)

What happen is this?

**Comment by null93** [comment]
@teguh02 Sorry for the late reply, I've been really busy. I think this bug only applies to Firefox. Thank you so much for bringing it to my attention. I found a fix and it should be out in the latest version.
