### ISSUE TITLE
Translation contribution

### ISSUE THREAD

**Issue by Lion-hk** [null93/milk-cookie-manager#74]
Chinese translation contribution. 99%.
[Chinese translation .zip](https://github.com/user-attachments/files/15811826/Chinese.translation.zip)

**Comment by null93** [comment]
Hey! Thank you for wanting to contribute. Would you like to open a PR for this?

**Comment by Lion-hk** [comment]
> Hey! Thank you for wanting to contribute. Would you like to open a PR for this?

sorry man，I am not a IT guy, don't know what's the meaning of PR, doing this just a hobby.
I am sorry can't help you more.  I very like to see your amazing plugin attract more Chinese users.

**Comment by null93** [comment]
No problem! Thank you for wanting to make the extension better. I did open the zip file you sent me and unfortunately, I cannot make sense of the JS file that you sent me.

In the next branch, I have translations as a work-in-progress. Checkout this file: https://github.com/null93/milk-cookie-manager/blob/next/static/_locales/ru/messages.json. I would basically need the same type of file for Chinese translations.

**Comment by Lion-hk** [comment]
I replaced the English with  Chinese in that JavaScript file.
I'll help you translate it when I get up tomorrow.
Are you Russian?

**Comment by Lion-hk** [comment]
@null93 Sorry man, I don't know how to submit files in your repository.
[messages.json](https://github.com/user-attachments/files/15849639/messages.json)
As a regular user, I would like to see numbers on the plugin's icon. It can tell me the change in the total amount.

**Comment by null93** [comment]
> I replaced the English with Chinese in that JavaScript file.
I'll help you translate it when I get up tomorrow.
Are you Russian?

Thank you! I am not Russian but I do speak it.

> @null93 Sorry man, I don't know how to submit files in your repository.
[messages.json](https://github.com/user-attachments/files/15849639/messages.json)
As a regular user, I would like to see numbers on the plugin's icon. It can tell me the change in the total amount.

No worries! This is more than enough, thank you for contributing!

Would you happen to know which locale this translation would be for? I am guessing `zh_CN` which is Chinese (simplified). Are you able to test this extension out for me before I release it to the public?

**Comment by Lion-hk** [comment]
Yes,Chinese (simplified). zh_CN
 I would love to test this awesome extension certainly，@ me or tell me where to follow .

**Comment by null93** [comment]
@Lion-hk Thank you very much! I packaged the extension with your Chinese translations. Not sure if you know how to install it so just in case, here are the steps:

1. Uninstall official MILK extension
2. Download and extract [milk_cookie_manager-2.4.0.zip](https://github.com/user-attachments/files/15894382/milk_cookie_manager-2.4.0.zip)
3. Go to chrome://extensions
4. Make sure "Developer mode" is enabled on the top-right of the page
5. Press "Load unpacked" button, and select the extracted folder

If you have any issues or need more clarification, feel free to respond here or you can send me an email at rafael@grigorian.org.

**Comment by Lion-hk** [comment]
It works，no bugs, except this ，need  texts to translate.

![No translation](https://github.com/null93/milk-cookie-manager/assets/117522220/ae977033-ec02-4907-a23a-37249e1abcd4)

**Comment by null93** [comment]
Good call, this was me being lazy lol. I will work on getting those into the translation file and message you after.

> @null93 If not @ you, can you receive a notification? I don't know how GitHub notifies owner.

It depends on your notification settings, but I will get the notification without you @'ing me.

**Comment by null93** [comment]
@Lion-hk Just finished templating out the text from the screenshot you sent. This file has all the translations that I would still need [needs-translation.json](https://github.com/user-attachments/files/15922345/needs-translation.json).

No rush! Thanks again!

**Comment by Mishasama** [comment]
@null93 It would be nice if you could add an option to change languages in the extension settings.

**Comment by Lion-hk** [comment]
> @null93 It would be nice if you could add an option to change languages in the extension settings.

他列有了语言文件，我没有提出来，但我心里觉得他应该会做的。

**Comment by null93** [comment]
> Some texts，such as HTTP-ONLY，I didn't translate，because it is used by high level user like IT guy，It's better to keep it in English mode.

@Lion-hk Thank you, I decided to leave them in English in the Russian translation as well.

> @null93 It would be nice if you could add an option to change languages in the extension settings.

> 他列有了语言文件，我没有提出来，但我心里觉得他应该会做的。

@Mishasama @Lion-hk Chrome does not support doing this with their [i18n (internationalization) api](https://developer.chrome.com/docs/extensions/reference/api/i18n). To change locale, you need to do it either on a system level or a browser level (for chrome extensions).

If I were to do this, I would have to ditch using their i18n api and make my own. Shouldn't be that hard to do, but there are downfalls to this method. For example, I will not be able to translate inside the manifest and only be able to make translations inside the UI.

I can give it a go and try, but depending on how much work its gonna be, I might stick with the i18n api.

**Comment by null93** [comment]
@Lion-hk @Mishasama I managed to make choosing the language an option. Test it out and let me know what you think :)

If everything looks good, I will package everything up and submit this as the next version.

[milk_cookie_manager-2.4.0.zip](https://github.com/user-attachments/files/15935416/milk_cookie_manager-2.4.0.zip)

**Comment by Lion-hk** [comment]
> I decided to leave them in English in the Russian translation as well.
No problem.
Good news, man ,it works perfect. It’s smooth to change language on EDGE browser, no bugs.
Is it ok to add a feature to display cookie numbers on the toolbar icon ? I think it is good.

**Comment by Lion-hk** [comment]
Like this.
![image](https://github.com/null93/milk-cookie-manager/assets/117522220/c6f3a4d5-77c0-46f6-8771-587fc2f900de)

**Comment by Lion-hk** [comment]
I missed this，it’s not very important，you could leave it if it isdifficult to handle.
![image](https://github.com/null93/milk-cookie-manager/assets/117522220/ca3b7aae-81c5-4106-a247-643ded5512d0)

**Comment by null93** [comment]
@Lion-hk Nice catch! I added a translation for that tooltip. I also added a link to your github profile in the special thanks section on the options page. Thanks again for your help.

> Is it ok to add a feature to display cookie numbers on the toolbar icon ? I think it is good.

Please open a new issue and I will try to get to it later. This is a passion project and I can only work on it whenever I have some down time. Between my full time job and family, it is sometimes hard to maintain these projects but I will do my best to get to it.

I released version 2.5.0 and submitted it to the chrome web store, it should be published in a couple days.

Please consider leaving a positive review on the Chrome web store if you like this extension :)

**Comment by Lion-hk** [comment]
And thanks for your work .  
Can you upload to EDGE ，I don't have Chrome on my computer and I don't like it, but I will download it for you.

**Comment by null93** [comment]
@Lion-hk 

No problem, I submitted it to the Microsoft edge web store, just waiting for it to be approved. Will you be able to test it out for me and let me know if everything works as expected?

**Comment by Lion-hk** [comment]
I tested the Google version on EDGE and nothing bad has happened so far.

**Comment by null93** [comment]
@Lion-hk just went live for edge!

https://microsoftedge.microsoft.com/addons/detail/milk-%E2%80%94-cookie-manager/jlephceclngfdednjllhjmjmbcjolhhl
